### ISSUE TITLE
cleverage/eav-manager image does not fully support cweagans/composer-patches

### ISSUE THREAD

**Issue by shavounet** [cleverage/dockerfiles#4]
**Test case**
* composer project, installed with `--prefer-dist`
* use cweagans/composer-patches to apply any patch on a vendor

**Problem**
* cweagans/composer-patches try to use `patch` with some options, but it fails:
```
Executing command (CWD): patch '-p4' --no-backup-if-mismatch -d '/app/vendor/instaclick/php-webdriver' < '/tmp/5c6431509a07d.patch'
patch: unrecognized option: no-backup-if-mismatch
```
* on the image, the version of patch seems to be `v1.28.4`, but on my local env (with works fine) it's `v2.7.6` and has much more options

**Comment by shavounet** [comment]
For information, a workaround is to use `--prefer-source` during install since cweagans/composer-patches will use git

**Comment by eheuje** [comment]
Done !
